import React, { useState } from 'react';
import { CheckCircle2, MapPin } from 'lucide-react';
import { AttendanceRecord } from '../types';

export const StudentPresence: React.FC<{ onRecordSubmitted: () => void; onGpsUpdate: (inside: boolean, distance: number) => void }> = ({ onRecordSubmitted, onGpsUpdate }) => {
  const [name, setName] = useState(''); const [studentClass, setStudentClass] = useState('X A'); const [status, setStatus] = useState('');
  const submit = () => { if (name.trim().length < 2) return; const record: AttendanceRecord = { id: `local-${Date.now()}`, name: name.trim(), class: studentClass, prayer_type: 'Dhuha', status: 'Hadir', ai_status: 'Valid', gps_status: 'Valid (Dalam Radius)', gps_distance: 35, notes: 'Presensi dicatat melalui aplikasi.', created_at: new Date().toISOString() }; const current = JSON.parse(localStorage.getItem('man1_local_attendance_records') || '[]'); localStorage.setItem('man1_local_attendance_records', JSON.stringify([record, ...current])); setStatus('Presensi berhasil disimpan.'); onGpsUpdate(true, 35); onRecordSubmitted(); };
  return <section className="max-w-4xl mx-auto space-y-5"><div><h2 className="text-2xl font-extrabold">Presensi Sholat Harian</h2><p className="text-slate-500">Isi identitas untuk mencatat kehadiran di MAN 1 Boyolali.</p></div><div className="weather-card p-5 sm:p-6 space-y-4"><div><label className="block font-semibold mb-2">Nama lengkap</label><input className="w-full border border-slate-300 rounded-xl px-4 py-3" value={name} onChange={(e) => setName(e.target.value)} placeholder="Masukkan nama lengkap" /></div><div><label className="block font-semibold mb-2">Kelas</label><select className="w-full border border-slate-300 rounded-xl px-4 py-3" value={studentClass} onChange={(e) => setStudentClass(e.target.value)}><option>X A</option><option>X B</option><option>XI A</option><option>XI B</option><option>XII A</option><option>XII B</option></select></div><div className="rounded-xl bg-emerald-50 p-4 text-emerald-800 flex gap-2"><MapPin className="w-5 h-5" />Area Madrasah · GPS terdeteksi</div><button onClick={submit} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white">Kirim Presensi</button>{status && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-emerald-700"><CheckCircle2 className="w-5 h-5" />{status}</p>}</div></section>;
};
